from typing import Protocol, List, Optional
from models import Patient, Doctor, Appointment

class Repository(Protocol):
    """Интерфейс для работы с хранилищем (общий для любых данных)."""
    def add(self, item: object) -> None: ...
    def get_by_id(self, item_id: int) -> Optional[object]: ...
    def get_all(self) -> List[object]: ...
    def delete(self, item_id: int) -> None: ...

class Notifier(Protocol):
    """Интерфейс для отправки уведомлений (принцип ISP)."""
    def send(self, message: str) -> None: ...